#!/bin/bash
# Setup logging with timestamps
exec > >(while IFS= read -r line || [ -n "$line" ]; do
    if [[ ! "$line" =~ ^\[[0-9]{4}-[0-9]{2}-[0-9]{2} ]]; then
        printf "[$(date +'%Y-%m-%d %H:%M:%S')] %s\n" "$line"
    else
        printf "%s\n" "$line"
    fi
done) 2>&1

set -e

echo "Building overdrive..."
go build -o bin/overdrive ./cmd/api-server
echo "Done."
